name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  next-app-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: format
        run: pnpm run prettier

      - name: lint
        run: pnpm run lint

      - name: TypeScript check
        run: pnpm run check-types
